### ISSUE TITLE
Fix the search bar UI

### ISSUE THREAD

**Issue by mudit023** [codemaniac-sahil/dictionary-web-app#11]
Hey👋
![image](https://user-images.githubusercontent.com/71916646/193463832-ba4f5379-f02b-46c4-84eb-eb0fc09f1965.png)

As you can see in the above image the placeholder text in the search box is not visible properly. Can I work on it?

**Comment by codemaniac-sahil** [comment]
Yes you can @mudit023

**Comment by mudit023** [comment]
Okay. Thanks

**Comment by codemaniac-sahil** [comment]
Add a functionality also when user press enter the result should be shown.

**Comment by mudit023** [comment]
Okay, I'll create a separate issue and PR for this.
