### ISSUE TITLE
Color Scheme And UI Improvements

### ISSUE THREAD

**Issue by sahadat-sk** [codemaniac-sahil/dictionary-web-app#34]
I think The color scheme of website can be improved, also general UX can be improved to make the site look more modern. Can I work on this ?

**Comment by codemaniac-sahil** [comment]
Yes @sahadat-sk

**Comment by tejus0** [comment]
@codemaniac-sahil  Can i also contribute in the improvements of the UI of the project?

**Comment by codemaniac-sahil** [comment]
@tejus0 this issue is already resolved.

**Comment by codemaniac-sahil** [comment]
@sahadat-sk would you please send PR again
