### ISSUE TITLE
want to Align center of Page ( following elements)

### ISSUE THREAD

**Issue by yasaswini999** [codemaniac-sahil/dictionary-web-app#39]
![image](https://user-images.githubusercontent.com/106906121/194711504-422915f9-f181-4f38-bd5a-23c6e4c4d70f.png)

**Comment by codemaniac-sahil** [comment]
@yasaswini999, You can work on this issue

**Comment by yasaswini999** [comment]
@codemaniac-sahil  the updated one is looking fine. should i make any changes to it?
I would like to add scroll to top feature what do you think?
![image](https://user-images.githubusercontent.com/106906121/194839241-5a075ea0-549e-4060-b277-b8011ad95587.png)
![image](https://user-images.githubusercontent.com/106906121/194839257-39ddeb14-4571-4100-b24a-85171b0e59a7.png)

**Comment by codemaniac-sahil** [comment]
yes @yasaswini999
