### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Sivam2313** [codemaniac-sahil/dictionary-web-app#40]
![previous](https://user-images.githubusercontent.com/100067002/194723980-be23ab3e-582c-4c3a-bd8a-bf26d1e7dff7.png)

Right now the meaning of the words and the examples do not show the parts of speech and all the meaning are shown in one paragraph.
It can be shown in a list form to make it more readable.

**Comment by codemaniac-sahil** [comment]
Okay @Sivam2313 you can work on this issue
