### ISSUE TITLE
want to change some of UI and the alignments

### ISSUE THREAD

**Issue by siddakbagga13** [codemaniac-sahil/dictionary-web-app#42]
hey @codemaniac-sahil assign this issue to me and also add hacktoberfest tag

**Comment by codemaniac-sahil** [comment]
@siddakbagga13 This issue is already assigned #39

**Comment by siddakbagga13** [comment]
I will change the button and do other alignment if you like you can merge
it

**Comment by codemaniac-sahil** [comment]
okay @siddakbagga13
