### ISSUE TITLE
Add Antonyms and Synonyms

### ISSUE THREAD

**Issue by Sivam2313** [codemaniac-sahil/dictionary-web-app#46]
It does not show antonyms and synonyms of the words.
I want to add that feature and fix the alignment of the search bar.
The alignment of the searchbar is not responsive.

![Screenshot 2022-10-13 051944](https://user-images.githubusercontent.com/100067002/195472052-82244478-182c-4815-8a60-cd02f9c74e10.png)

![Screenshot 2022-10-13 051920](https://user-images.githubusercontent.com/100067002/195472061-75b140bb-5798-4753-bb93-0930e474ff31.png)

**Comment by codemaniac-sahil** [comment]
Yes @Sivam2313 please fix this.
