### ISSUE TITLE
Smooth over hover state animations

### ISSUE THREAD

**Issue by wkan17012021** [codemaniac-sahil/dictionary-web-app#58]
Hello @codemaniac-sahil , this is a clever app- nice work! 
I would like to contribute by adding some css to smooth over the animations for the search button and social media buttons.
Please could you assign this issue to me with the Hacktoberfest 2022 tag?

**Comment by codemaniac-sahil** [comment]
@wkan17012021, You can start work on this issue

**Comment by wkan17012021** [comment]
Thanks @codemaniac-sahil , PR submitted for review!
